# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='grade',
            field=models.CharField(choices=[('PES', 'PES'), ('ASS', 'ASS'), ('MAB', 'MAB'), ('MAA', 'MAA'), ('MCB', 'MCB'), ('MCA', 'MCA'), ('PROF', 'PROF')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
