# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_enseignant_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='grade',
            field=models.CharField(choices=[('P', 'PES'), ('A', 'ASS'), ('M', 'MAB'), ('M', 'MAA'), ('M', 'MCB'), ('M', 'MCA'), ('P', 'PROF')], max_length=1),
        ),
    ]
