# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 00:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('person', '0003_auto_20180603_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='etudiant',
            name='anne',
            field=models.IntegerField(choices=[(1, 'L1'), (2, 'L2'), (3, 'L3'), (4, 'M1'), (5, 'M2'), (6, 'D')], default=1),
            preserve_default=False,
        ),
    ]
