# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20180604_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='anne',
            field=models.IntegerField(choices=[(1, 'L1'), (2, 'L2'), (3, 'L3'), (4, 'M1 SITW'), (4, 'M1 RSD'), (4, 'M1 RESIM'), (4, 'M1 ADSI'), (4, 'M1 IIPE'), (4, 'M2 SITW'), (4, 'M2 RSD'), (4, 'M2 RESIM'), (4, 'M2 ADSI'), (4, 'M2 IIPE'), (6, 'D')]),
        ),
    ]
