# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 00:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20180604_0018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='enseignant',
            new_name='Adminstration',
        ),
    ]
