# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 00:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20180604_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='anne',
            new_name='parcour',
        ),
    ]
