# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_matierre'),
    ]

    operations = [
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_cc', models.FloatField()),
                ('note_examen', models.FloatField()),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.etudiant')),
                ('matierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.matierre')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together=set([('matierre', 'etudiant')]),
        ),
    ]
