# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_note_moyenne'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note_cc',
            new_name='note_cour',
        ),
        migrations.AddField(
            model_name='note',
            name='note_td',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='note_tp',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
