# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0011_auto_20180604_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='matierre',
            name='responsable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.Adminstration'),
            preserve_default=False,
        ),
    ]
