# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0013_recours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recours',
            old_name='semstre',
            new_name='recours',
        ),
    ]
