# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0017_auto_20180604_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recours',
            name='accepte',
            field=models.CharField(choices=[('1', 'ACCEPTÉ'), ('2', 'REFFUSÉ'), ('3', 'PAS DE DESSISION')], max_length=1),
        ),
    ]
