# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0018_auto_20180604_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
