# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0020_auto_20180604_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
    ]
