# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0021_auto_20180604_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpc', models.ImageField(upload_to='')),
                ('semsetre', models.CharField(choices=[('1', 's1'), ('2', 's2')], max_length=1)),
                ('parcour', models.IntegerField(choices=[(1, 'L1'), (2, 'L2'), (3, 'L3'), (4, 'M1 SITW'), (4, 'M1 RSD'), (4, 'M1 RESIM'), (4, 'M1 ADSI'), (4, 'M1 IIPE'), (4, 'M2 SITW'), (4, 'M2 RSD'), (4, 'M2 RESIM'), (4, 'M2 ADSI'), (4, 'M2 IIPE'), (6, 'D')])),
                ('responsable', models.ManyToManyField(related_name='responsable', to='person.Adminstration')),
            ],
        ),
    ]
