# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0022_cpc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpc',
            name='date_cpc',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cpc',
            name='parcour',
            field=models.IntegerField(choices=[(1, 'L1'), (2, 'L2'), (3, 'L3'), (4, 'M1 SITW'), (4, 'M1 RSD'), (4, 'M1 RESIM'), (4, 'M1 ADSI'), (4, 'M1 IIPE'), (5, 'M2 SITW'), (5, 'M2 RSD'), (5, 'M2 RESIM'), (5, 'M2 ADSI'), (5, 'M2 IIPE'), (10, 'D')]),
        ),
        migrations.RemoveField(
            model_name='cpc',
            name='responsable',
        ),
        migrations.AddField(
            model_name='cpc',
            name='responsable',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to='person.Adminstration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='parcour',
            field=models.IntegerField(choices=[(1, 'L1'), (2, 'L2'), (3, 'L3'), (4, 'M1 SITW'), (4, 'M1 RSD'), (4, 'M1 RESIM'), (4, 'M1 ADSI'), (4, 'M1 IIPE'), (5, 'M2 SITW'), (5, 'M2 RSD'), (5, 'M2 RESIM'), (5, 'M2 ADSI'), (5, 'M2 IIPE'), (10, 'D')]),
        ),
        migrations.AlterField(
            model_name='matierre',
            name='parcour',
            field=models.IntegerField(choices=[(1, 'L1'), (2, 'L2'), (3, 'L3'), (4, 'M1 SITW'), (4, 'M1 RSD'), (4, 'M1 RESIM'), (4, 'M1 ADSI'), (4, 'M1 IIPE'), (5, 'M2 SITW'), (5, 'M2 RSD'), (5, 'M2 RESIM'), (5, 'M2 ADSI'), (5, 'M2 IIPE'), (10, 'D')]),
        ),
        migrations.AlterField(
            model_name='matierre',
            name='responsable',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='person.Adminstration'),
        ),
        migrations.AlterField(
            model_name='note',
            name='etudiant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='person.etudiant'),
        ),
        migrations.AlterField(
            model_name='note',
            name='matierre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='person.matierre'),
        ),
    ]
