# Generated by Django 2.0.4 on 2018-06-11 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0024_remove_cpc_cpc'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocSigner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_doc', models.CharField(max_length=200)),
                ('url_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('destination', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='person.Adminstration')),
            ],
        ),
    ]
